### ISSUE TITLE
Add support PureChat for add variable {GROUP}

### ISSUE THREAD

**Issue by SuperAdam47** [UnknownBallin/StaffJoin#1]
https://github.com/UnknownBallin/StaffJoin/blob/861072cfc20f29b9fc1eb23c88cc5a59667ce0a7/resources/config.yml#L8

**Comment by UnknownBallin** [comment]
Thanks for the request, took me a bit but I worked quickly, I'll be sure to fix up the plugin since the latest version only works if PP is installed.
